In [1]:
import pandas as pd
import plotly.express as px

pd.options.plotting.backend = "plotly"
from IPython.display import display, HTML

In [2]:
df = pd.read_excel("../data/05. Database RP May 2025 - AC REGISTER.xlsx", sheet_name="Raw", skiprows=1)

In [3]:
df = df.iloc[:, 1:]
display(HTML(df.head().to_html()))

In [4]:
df['CATERING']

0         363.075018
1         363.075018
2         365.479488
3         382.310780
4         360.670548
             ...
110775    309.880000
110776    236.790000
110777    243.570000
110778    449.540000
110779    296.990000
Name: CATERING, Length: 110780, dtype: float64

In [5]:
df[df['CATERING']==0]

,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,...,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
117,2024,JAN,AC738,GA0107.PLM-CGK.[PLM-PLM],DOM,DOM_2 (JKT),CGK-PLM-CGK,PLM-CGK,PKGNE,27012024,...,0.00,0.00,0.000000,0.000000,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
395,2024,JAN,AC738,GA0146.CGK-BTJ.[CGK-CGK],DOM,DOM_2 (JKT),CGK-BTJ-CGK,CGK-BTJ,PKGMP,2012024,...,0.00,0.00,0.000000,0.000000,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2166,2024,JAN,AC738,GA0448.CGK-SUB-KOE.[CGK-KOE],DOM,DOM_3 (SUB),CGK-SUB-KOE-SUB-CGK,CGK-SUB-KOE,PKGNQ,30012024,...,1.93,71.41,546.050867,2723.444017,Q1,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
2169,2024,JAN,AC738,GA0448.CGK-SUB-KOE.[CGK-KOE],DOM,DOM_3 (SUB),CGK-SUB-KOE-SUB-CGK,CGK-SUB-KOE,PKGNF,1012024,...,0.00,11.58,89.624403,0.000000,Q1,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
2172,2024,JAN,AC738,GA0448.CGK-SUB-KOE.[CGK-KOE],DOM,DOM_3 (SUB),CGK-SUB-KOE-SUB-CGK,CGK-SUB-KOE,PKGNC,2012024,...,3.86,15.44,184.598585,1177.938116,Q1,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108603,2025,MAY,AC738,GA0140.CGK-BTJ.[CGK-CGK],DOM,DOM_2 (JKT),CGK-BTJ-CGK,CGK-BTJ,PKGNQ,24052025,...,0.00,0.00,0.000000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
108899,2025,MAY,AC738,GA0313.SUB-CGK.[SUB-SUB],DOM,DOM_3 (SUB),CGK-SUB-CGK,SUB-CGK,PKGMX,20052025,...,0.00,0.00,0.000000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
109112,2025,MAY,AC738,GA0288.CGK-TNJ.[CGK-CGK],DOM,DOM_2 (JKT),CGK-TNJ-CGK,CGK-TNJ,PKGNH,5052025,...,0.00,0.00,0.000000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
109171,2025,MAY,AC738,GA0635.DJJ-TIM.[DJJ-DJJ],DOM,DOM_4 (UPG),TIM-DJJ-TIM,DJJ-TIM,PKGNQ,22052025,...,0.00,0.00,0.000000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
109807,2025,MAY,AC738,GA0689.UPG-MDC.[UPG-UPG],DOM,DOM_4 (UPG),MDC-UPG-MDC,UPG-MDC,PKGFJ,25052025,...,0.00,0.00,0.000000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

In [6]:
df_num = df.select_dtypes(include=["number"])
corr = df_num.corrwith(df_num['CATERING']).sort_values(ascending=False).dropna()
corr.head(50)

/Users/liaristiana/opt/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/liaristiana/opt/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

CATERING                                        1.000000
TOTAL DIRECT TRAFFIC COSTS                      0.908665
TOTAL DIRECT COSTS                              0.795708
TOTAL DIRECT AND INDIRECT COSTS                 0.790626
TOTAL COSTS                                     0.784365
TOTAL BO COSTS                                  0.781963
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.781617
RTK PASSENGER (000)                             0.778204
RPK (000)                                       0.777575
RPK (000) Y CLASS                               0.773854
CABIN CREW TRAVEL                               0.770370
TOTAL DIRECT FLIGHT COSTS                       0.763169
FUEL BURN (IN LITER)                            0.758147
FUEL AIRCRAFT                                   0.757307
RTK (000)                                       0.751982
ATK (000)                                       0.749078
ATK PASSENGER (000)                             0.745818
ASK (000)                                       0.745320
ASK (000) Y CLASS                               0.742473
LEASE AIRCRAFT                                  0.730367
ADMINISTRATION HO                               0.730068
TOTAL FLEET COST                                0.729273
PASSENGER REVENUE NETT                          0.723269
PASSENGER REVENUE GROSS                         0.722918
NETT REVENUES                                   0.721905
MAINTENANCE RESERVE                             0.718665
CABIN CREW PERSON                               0.716376
ASK (000) C CLASS                               0.713496
INSURANCE                                       0.713169
COCKPIT CREW TRAVEL                             0.711262
TOTAL INDIRECT COSTS                            0.706579
FLIGHT KILOMETERS                               0.705789
PASSENGER REVENUE NETT Y CLASS                  0.702972
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.701674
PASSENGER REVENUE GROSS Y CLASS                 0.701636
BLOCK HOURS                                     0.700469
OTHER REVENUE PASSENGER                         0.700144
FLIGHT HOURS                                    0.699282
RPK (000) C CLASS                               0.691233
COCKPIT CREW PERSON                             0.685768
VARIABLE MAINTENANCE                            0.656220
MARKETING                                       0.644023
OTHER REVENUE                                   0.638556
LANDING                                         0.625374
HANDLING                                        0.622467
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.619394
PASSENGER REVENUE GROSS C CLASS                 0.619353
PASSENGER REVENUE NETT C CLASS                  0.612361
SEAT OFFERED                                    0.596043
SEAT OFFERED Y CLASS                            0.588832
dtype: float64

In [7]:
df1 = df[(df['PASSENGER CARRIED'] != 0) & (df['BLOCK HOURS']!=0) & 
        (df['ON BOARD SERVICE']!=0) & (df['CATERING']!=0)].copy()
len(df1)

107959

In [8]:
SELECTED_FEATURES = [
                     'PASSENGER CARRIED', 
                     'ATK (000)', 'ATK PASSENGER (000)', 'ASK (000)', 'ASK (000) Y CLASS',
                     'FLIGHT ROUTE', 'SERVICE TYPE', 'Region']

df1[SELECTED_FEATURES]

,PASSENGER CARRIED,ATK (000),ATK PASSENGER (000),ASK (000),ASK (000) Y CLASS,FLIGHT ROUTE,SERVICE TYPE,Region
0,151,3.638548,3.000871,30.942,28.650,CGK-TKG,DOM,DOM_WEST
1,151,3.638548,3.000871,30.942,28.650,CGK-TKG,DOM,DOM_WEST
2,152,3.638548,3.000871,30.942,28.650,CGK-TKG,DOM,DOM_WEST
3,159,3.638548,3.000871,30.942,28.650,CGK-TKG,DOM,DOM_WEST
4,150,3.638548,3.000871,30.942,28.650,CGK-TKG,DOM,DOM_WEST
...,...,...,...,...,...,...,...,...
110775,158,6.401000,5.279000,54.432,50.400,KDI-UPG,DOM,DOM_EAST
110776,114,8.077000,6.991000,72.080,68.688,CGK-YIA,DOM,DOM_WEST
110777,118,8.077000,6.991000,72.080,68.688,YIA-CGK,DOM,DOM_WEST
110778,171,20.974000,18.152000,187.170,178.362,CGK-AMI,DOM,DOM_EAST
110779,91,20.974000,18.152000,187.170,178.362,AMI-CGK,DOM,DOM_EAST

In [9]:
X = df1[SELECTED_FEATURES].copy()
y = df1['CATERING'].copy()

In [10]:
CATEGORICAL_COLS = ['SERVICE TYPE', 'FLIGHT ROUTE', 'Region']
NUMERIC_COLS = list(set(SELECTED_FEATURES) - set(CATEGORICAL_COLS))
NUMERIC_COLS

['ASK (000)',
 'ASK (000) Y CLASS',
 'PASSENGER CARRIED',
 'ATK (000)',
 'ATK PASSENGER (000)']

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
from sklearn.preprocessing import OneHotEncoder

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [13]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(X_train[CATEGORICAL_COLS])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [14]:
X_train_encoded = encoder.transform(X_train[CATEGORICAL_COLS])
X_test_encoded = encoder.transform(X_test[CATEGORICAL_COLS])

In [15]:
encoded_cols = encoder.get_feature_names_out(CATEGORICAL_COLS)

X_train_encoded = pd.DataFrame(X_train_encoded, columns=encoded_cols, index=X_train.index)
X_test_encoded = pd.DataFrame(X_test_encoded, columns=encoded_cols, index=X_test.index)

In [16]:
X_train_final = pd.concat([X_train[NUMERIC_COLS], X_train_encoded], axis=1)
X_test_final = pd.concat([X_test[NUMERIC_COLS], X_test_encoded], axis=1)

In [17]:
from xgboost import XGBRegressor

In [18]:
model = XGBRegressor(n_estimators=2000, learning_rate=0.5, objective="reg:squarederror")
model.fit(X_train_final, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.5, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=2000,
             n_jobs=None, num_parallel_tree=None, ...)

In [19]:
y_pred = model.predict(X_test_final)

In [20]:
mean_absolute_percentage_error(y_test, y_pred)

0.0680749281499688