In [1]:
import pandas as pd
import plotly.express as px

pd.options.plotting.backend = "plotly"
from IPython.display import display, HTML

In [2]:
df = pd.read_excel("../data/05. Database RP May 2025 - AC REGISTER.xlsx", sheet_name="Raw", skiprows=1)

In [3]:
df = df.iloc[:, 1:]
display(HTML(df.head().to_html()))

In [4]:
df['ON BOARD SERVICE']

0           0.990068
1           0.990068
2           0.996625
3           1.042522
4           0.983512
             ...
110775     32.163000
110776     29.284000
110777     30.312000
110778    114.064000
110779     60.701000
Name: ON BOARD SERVICE, Length: 110780, dtype: float64

In [5]:
df[df['ON BOARD SERVICE']==0]

,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,...,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
117,2024,JAN,AC738,GA0107.PLM-CGK.[PLM-PLM],DOM,DOM_2 (JKT),CGK-PLM-CGK,PLM-CGK,PKGNE,27012024,...,0.0,0.0,0.0,0.0,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
395,2024,JAN,AC738,GA0146.CGK-BTJ.[CGK-CGK],DOM,DOM_2 (JKT),CGK-BTJ-CGK,CGK-BTJ,PKGMP,2012024,...,0.0,0.0,0.0,0.0,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2520,2024,JAN,AC738,GA0572.CGK-BPN.[CGK-CGK],DOM,DOM_2 (JKT),CGK-BPN-CGK,CGK-BPN,PKGFI,1012024,...,0.0,0.0,0.0,0.0,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2983,2024,JAN,AC738,GA0617.UPG-CGK.[UPG-UPG],DOM,DOM_4 (UPG),CGK-UPG-CGK,UPG-CGK,PKGMP,30012024,...,0.0,0.0,0.0,0.0,Q1,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
3002,2024,JAN,AC738,GA0617.UPG-CGK.[UPG-UPG],DOM,DOM_4 (UPG),CGK-UPG-CGK,UPG-CGK,PKGFS,6012024,...,0.0,0.0,0.0,0.0,Q1,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110092,2025,MAY,AC738,GA0324.CGK-SUB.[DPS-SUB],DOM,DOM_3 (SUB),CGK-SUB-CGK,CGK-SUB,PKGNH,14052025,...,0.0,0.0,0.0,0.0,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110706,2025,MAY,AC330,GA0961.MED-CGK.[MED-CGK],INT,INT_5 (AMS)-MEA,CGK-MED-CGK,MED-CGK,PKGPY,28052025,...,0.0,0.0,0.0,0.0,Q2,ACTUAL,A333,PAX & CARGO,MEA,MEA
110708,2025,MAY,AC334,GA0993.JED-CGK.[JED-CGK],INT,INT_5 (AMS)-MEA,CGK-JED-CGK,JED-CGK,PKGHC,30052025,...,0.0,0.0,0.0,0.0,Q2,ACTUAL,A333,PAX & CARGO,MEA,MEA
110752,2025,MAY,AC738,GA0830.CGK-SIN.[CGK-SIN],INT,INT_1 (SIN),CGK-SIN-CGK,CGK-SIN,PKGMD,25052025,...,0.0,0.0,0.0,0.0,Q2,ACTUAL,B738NG,PAX & CARGO,ASA,INT
110769,2025,MAY,AC33E,GA6055.UPG-CGK.[UPG-CGK],DOM,DOM_4 (UPG),CGK-UPG-CGK,UPG-CGK,PKGPF,29052025,...,0.0,0.0,0.0,0.0,Q2,ACTUAL,A333,PAX & CARGO,IBT,DOM_EAST

In [6]:
df_num = df.select_dtypes(include=["number"])
corr = df_num.corrwith(df_num['ON BOARD SERVICE']).sort_values(ascending=False).dropna()
corr.head(50)

/Users/liaristiana/opt/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/liaristiana/opt/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

ON BOARD SERVICE                                1.000000
CABIN CREW PERSON                               0.735612
TOTAL INDIRECT COSTS                            0.715298
RTK PASSENGER (000)                             0.701656
RPK (000)                                       0.701532
RPK (000) Y CLASS                               0.699465
COCKPIT CREW PERSON                             0.682245
RTK (000)                                       0.677847
ATK PASSENGER (000)                             0.665573
ASK (000)                                       0.665534
ASK (000) Y CLASS                               0.665486
FUEL BURN (IN LITER)                            0.663557
ATK (000)                                       0.662201
TOTAL COSTS                                     0.651460
TOTAL DIRECT AND INDIRECT COSTS                 0.649708
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.647650
TOTAL BO COSTS                                  0.646527
TOTAL DIRECT COSTS                              0.640678
TOTAL DIRECT FLIGHT COSTS                       0.638031
FLIGHT KILOMETERS                               0.637756
FUEL AIRCRAFT                                   0.633393
ADMINISTRATION HO                               0.630090
FLIGHT HOURS                                    0.626933
PASSENGER REVENUE GROSS                         0.626246
PASSENGER REVENUE NETT                          0.626202
TOTAL FLEET COST                                0.624318
BLOCK HOURS                                     0.624010
NETT REVENUES                                   0.623822
MAINTENANCE RESERVE                             0.622351
CABIN CREW TRAVEL                               0.615145
LEASE AIRCRAFT                                  0.615116
ASK (000) C CLASS                               0.614057
PASSENGER REVENUE GROSS Y CLASS                 0.613587
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.613539
RPK (000) C CLASS                               0.611253
PASSENGER REVENUE NETT Y CLASS                  0.610515
AIR TRAFFIC CONTROL                             0.595915
VARIABLE MAINTENANCE                            0.582395
COCKPIT CREW TRAVEL                             0.568504
TOTAL DIRECT TRAFFIC COSTS                      0.566845
AIRCRAFT MAINTENANCE                            0.551351
INSURANCE                                       0.528883
PASSENGER REVENUE NETT C CLASS                  0.520971
LANDING                                         0.513227
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.511201
PASSENGER REVENUE GROSS C CLASS                 0.511188
OTHER REVENUE PASSENGER                         0.498606
MARKETING                                       0.475181
CATERING                                        0.474741
OTHER REVENUE                                   0.470554
dtype: float64

In [7]:
df1 = df[(df['PASSENGER CARRIED'] != 0) & (df['BLOCK HOURS']!=0) & 
        (df['ON BOARD SERVICE']!=0) & (df['CATERING']!=0)].copy()
len(df1)

107959

In [8]:
SELECTED_FEATURES = ['PASSENGER CARRIED',
                    'ATK PASSENGER (000)', 'ASK (000)', 'ASK (000) Y CLASS', 'ATK (000)',
                    'CABIN CREW PERSON', 'COCKPIT CREW PERSON'
                    ]

df1[SELECTED_FEATURES]

# performed worse when combined with these categorical columns:  'FLIGHT ROUTE', 'SERVICE TYPE', 'Region'

,PASSENGER CARRIED,ATK PASSENGER (000),ASK (000),ASK (000) Y CLASS,ATK (000),CABIN CREW PERSON,COCKPIT CREW PERSON
0,151,3.000871,30.942,28.650,3.638548,46.533742,299.002595
1,151,3.000871,30.942,28.650,3.638548,46.533742,388.627069
2,152,3.000871,30.942,28.650,3.638548,46.533742,279.797350
3,159,3.000871,30.942,28.650,3.638548,46.533742,331.011335
4,150,3.000871,30.942,28.650,3.638548,46.533742,292.600847
...,...,...,...,...,...,...,...
110775,158,5.279000,54.432,50.400,6.401000,127.997000,399.652000
110776,114,6.991000,72.080,68.688,8.077000,170.510000,515.661000
110777,118,6.991000,72.080,68.688,8.077000,170.766000,530.608000
110778,171,18.152000,187.170,178.362,20.974000,435.184000,896.802000
110779,91,18.152000,187.170,178.362,20.974000,436.849000,993.956000

In [9]:
X = df1[SELECTED_FEATURES].copy()
y = df1['ON BOARD SERVICE'].copy()

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
from sklearn.preprocessing import OneHotEncoder

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

## XGBoost

In [13]:
from xgboost import XGBRegressor

In [14]:
model = XGBRegressor(n_estimators=2000, learning_rate=0.5, objective="reg:squarederror")
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.5, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=2000,
             n_jobs=None, num_parallel_tree=None, ...)

In [15]:
y_pred = model.predict(X_test)

In [16]:
mean_absolute_percentage_error(y_test, y_pred)

0.10803046518969221