In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../05. Database RP May 2025 - AC REGISTER.xlsx", sheet_name="Raw", skiprows=1)
df = df.iloc[:, 1:]
df.head()

,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,...,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,30012024,...,0.573,28.268,382.164660,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,31012024,...,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,1012024,...,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,2012024,...,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,19012024,...,0.573,28.077,448.429472,30.733542,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST

In [ ]:
cols = ["YEAR", "PERIODE", "AIRCRAFT TYPE", "FLIGHT NUMBER_CITYPAIR", "SERVICE TYPE", "SUB-SERVICE", 
        "ROUNDTRIPROUTE", "FLIGHT ROUTE", "AC REG", "Region", "QUARTER", "GA Service","AIRCRAFT TYPE GROUPING"]

In [7]:
df1 = df.loc[:, cols]
df1.drop_duplicates(inplace=True)

In [9]:
unique_dict = {col: df1[col].unique().tolist() for col in df1.columns}

# Find the maximum length among all unique value lists
max_len = max(len(v) for v in unique_dict.values())

# Pad lists with None to ensure all have the same length
for col in unique_dict:
    unique_dict[col].extend([None] * (max_len - len(unique_dict[col])))

# Create the new DataFrame
unique_df = pd.DataFrame(unique_dict)
unique_df

,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,Region,QUARTER,GA Service
0,2024.0,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,DOM_WEST,Q1,IBB
1,2025.0,FEB,AC773,GA0073.TKG-CGK.[TKG-CGK],INT,INT_5 (AMS)-EUR,CGK-AMS-CGK,TKG-CGK,PKGFJ,INT,Q2,EUR
2,NaN,MAR,AC73G,GA0088.CGK-AMS.[CGK-AMS],None,DOM_1 (MES),CGK-PLM-CGK,CGK-AMS,PKGNA,DOM_EAST,Q3,IBT
3,NaN,APR,AC330,GA0089.AMS-CGK.[AMS-CGK],None,DOM_3 (SUB),CGK-MES-CGK,AMS-CGK,PKGMW,MEA,Q4,SWP
4,NaN,MAY,AC33R,GA0102.CGK-PLM.[CGK-PLM],None,DOM_3 (DPS),CGK-DJB-CGK,CGK-PLM,PKGNN,None,None,ASA
...,...,...,...,...,...,...,...,...,...,...,...,...
1083,NaN,None,None,GA0830.CGK-SIN.[CGK-SIN],None,None,None,None,None,None,None,None
1084,NaN,None,None,GA1800.CGK-MES.[CGK-MES],None,None,None,None,None,None,None,None
1085,NaN,None,None,GA6004.CGK-UPG.[CGK-UPG],None,None,None,None,None,None,None,None
1086,NaN,None,None,GA4022.CGK-DPS.[CGK-DPS],None,None,None,None,None,None,None,None
1087,NaN,None,None,GA4344.AMI-CGK.[AMI-CGK],None,None,None,None,None,None,None,None

In [11]:
len(unique_df)

1088

In [13]:
unique_df.to_csv("df_filter1.csv", index=False)